feat: Update button style to new Elm Theme
edx/edx-mobile-marketplace-android pull request #32
Opened 2024-08-13 14:32 UTC by omerhabib26

### Description:

- Define generic button style for the whole app
- Remove the custom/random button initialization
- Make dialog's buttons appearance close to native

fix: LEARNER-10084

Ref: https://www.figma.com/design/q6z6cpJsbBBcnPZLPS7KEu/Marketplace-Visual-Design?node-id=3932-2331&t=C9RFjYFEPRxwC2Hc-0

2024-09-30 10:13 UTC, dixidroid requested changes

2024-10-03 15:34 UTC, farhan-arshad-dev requested changes
Need product approval for the design changes on the following files:

- Fullscreen(error message).
- ChapterEndDialogScreen
- SetupCourseAccessErrorButtons
- CourseOutlineScreen
- NotSupportedUnitFragment
- DashboardGalleryView(Find new course button)
- DiscussionThreadsFragment
- CalendarAccessDialogFragment

2024-10-04 19:32 UTC, omerhabib26 commented on course/src/main/java/org/openedx/course/presentation/ui/CourseVideosUI.kt
> +            mutableStateOf(true)
updated by mistake, reverted.

2024-10-09 08:15 UTC, farhan-arshad-dev commented on core/src/main/java/org/openedx/core/ui/ComposeCommon.kt
> +        onClick = onClick,
decided to use trailing commas.

2024-10-09 08:17 UTC, farhan-arshad-dev commented on core/src/main/java/org/openedx/core/ui/ComposeCommon.kt
> +    backgroundColor: Color = Color.White,
still pending, we can cover this with Standardized Styling System work.

2024-10-09 08:19 UTC, farhan-arshad-dev commented on core/src/main/java/org/openedx/core/ui/ComposeCommon.kt
> +            .heightIn(min = 42.dp),
still pending.

2024-10-09 08:25 UTC, farhan-arshad-dev commented on dashboard/src/main/java/org/openedx/courses/presentation/DashboardGalleryView.kt
> -            .fillMaxWidth()
still pending.

2024-10-09 08:40 UTC, farhan-arshad-dev commented
> Need product approval for the design changes on the following files:
> 
> * Fullscreen(error message).
> * ChapterEndDialogScreen
> * SetupCourseAccessErrorButtons
> * CourseOutlineScreen
> * NotSupportedUnitFragment
> * DashboardGalleryView(Find new course button)
> * DiscussionThreadsFragment
> * CalendarAccessDialogFragment

Have we received product approval for these changes?

Also need to address 2 comments, other than that ready to be approved.

2024-10-09 14:21 UTC, farhan-arshad-dev approved these changes

2024-10-10 06:14 UTC, farhan-arshad-dev approved these changes

2024-10-10 14:52 UTC, dixidroid approved these changes

2024-10-10 15:29 UTC, merged