fix: catch exception when parsing file for transcripts
edx/edx-mobile-marketplace-android pull request #42
Opened 2024-08-26 12:58 UTC by dixidroid

try/catch block was missed for the second case when transcriptInputStream == null

2024-09-09 09:51 UTC, farhan-arshad-dev requested changes

2024-09-09 09:51 UTC, farhan-arshad-dev commented on core/src/main/java/org/openedx/core/module/TranscriptManager.kt
> +                    } catch (e: Exception) {
[Optional] UI/UX Improvement
Space underneath the video player if the app is unable to load the transcript.

![image](https://github.com/user-attachments/assets/549491f2-e6d3-4dae-bea4-85e3a6c3b4dd)

2024-09-10 16:04 UTC, dixidroid commented on core/src/main/java/org/openedx/core/module/TranscriptManager.kt
> +                    } catch (e: Exception) {
done

2024-09-11 06:03 UTC, farhan-arshad-dev commented on core/src/main/java/org/openedx/core/module/TranscriptManager.kt
>                  getInputStream(downloadLink)?.let {
As discussed, we will cover this in a separate PR.

2024-09-11 06:03 UTC, farhan-arshad-dev commented on core/src/main/java/org/openedx/core/module/TranscriptManager.kt
> +                    } catch (e: Exception) {
As discussed, we will cover this in a separate PR.

2024-09-11 06:30 UTC, farhan-arshad-dev approved these changes

2024-09-12 05:15 UTC, merged