fix:Customize the Firebase plugin to meet its data guidelines.
edx/edx-mobile-marketplace-android pull request #49
Opened 2024-09-10 11:02 UTC by omerhabib26

### Description:

- Update Event's data triggering on Firebase according to its data guidelines
- Update the segment and destination library
- override the execution to update the data according to firebase data guidelines
- Remove extra space from IAP analytics

fix: LEARNER-10190

2024-09-11 10:01 UTC, farhan-arshad-dev requested changes

2024-09-11 10:01 UTC, farhan-arshad-dev commented on app/src/main/java/org/openedx/app/analytics/SegmentAnalytics.kt
> +            tracker.find(FirebaseDestination::class)?.add(object : EventPlugin {
deserve doc string, why need to use the find function, cuz otherwise the app leads to a crash.

2024-09-11 12:04 UTC, omerhabib26 commented on app/src/main/java/org/openedx/app/analytics/AnalyticsUtils.kt
> +        return value.replace(Regex("[:\\- ]+"), "_").take(40)
Regex will handle the double underscore "__"

2024-09-12 16:16 UTC, farhan-arshad-dev approved these changes
Just need to address Igor's comments, other than that LGTM.

2024-09-13 05:21 UTC, merged