chore: Elm theme Improvements on Discussion Module
edx/edx-mobile-marketplace-android pull request #59
Opened 2024-10-04 16:00 UTC by omerhabib26

### Description:

- Update Text, icons colors and button according to elm theme

fix: LEARNER-10080

![Uploading Screenshot_20241004-204414_edX.jpg…]()

2024-10-04 16:12 UTC, omerhabib26 commented
These test cases are fixed in https://github.com/edx/edx-mobile-marketplace-android/pull/55

2024-10-08 15:52 UTC, HamzaIsrar12 requested changes
**Manual Review:**

- The follow button is functioning perfectly (light/dark).
- The selected state color for the like button needs updating; it currently appears dim (light/dark).
- The disabled state for the send button only affects the background orange color and not the white icon (dark).
- The create button does not have a disabled state (light/dark).

2024-10-09 16:56 UTC, HamzaIsrar12 approved these changes
Looks good to me. 🏎️ 

Note: Please rebase it to fix the test cases.

2024-10-10 07:24 UTC, dixidroid approved these changes

2024-10-10 14:07 UTC, merged