feat: Added offline support for CourseEnrollmentDetails API
edx/edx-mobile-marketplace-android pull request #69
Opened 2024-11-19 12:09 UTC by omerhabib26

### Description: 

- Store CourseEnrollmentDetails API response in DB for offline mode
- Return DB response if device is offline

fix: LEARNER-10282

2024-11-25 14:33 UTC, dixidroid approved these changes

2024-12-03 12:21 UTC, farhan-arshad-dev requested changes

2024-12-03 12:21 UTC, farhan-arshad-dev commented on app/src/main/java/org/openedx/app/room/Migrations.kt
> +        override fun migrate(database: SupportSQLiteDatabase) {
use `db` instead of `database` to make the naming convention consistent.

2024-12-03 12:21 UTC, farhan-arshad-dev commented on app/src/main/java/org/openedx/app/room/Migrations.kt
> +            database.execSQL("DROP TABLE IF EXISTS course_enrollment_details_table")
Specific use-case to delete the old table?

cuz this will delete the data along with the table structure. also already using `CREATE TABLE IF NOT EXISTS` in the next statement.

2024-12-03 12:21 UTC, farhan-arshad-dev commented on app/src/main/java/org/openedx/app/room/Migrations.kt
> +    }
I believe it can be removed, as the course_modes_table is not being used elsewhere. 

also using `CourseModeDB` as Column.

2024-12-03 12:21 UTC, farhan-arshad-dev commented on core/src/main/java/org/openedx/core/data/model/room/discovery/EnrolledCourseEntity.kt
> +    val coursewareAccess: CoursewareAccessDb?,
The code change in this file can be reverted.

2024-12-03 12:21 UTC, farhan-arshad-dev commented on app/src/main/java/org/openedx/app/room/AppDatabase.kt
> +import org.openedx.core.data.model.room.CourseEnrollmentDetailsEntity
needs auto-format.

2024-12-06 05:47 UTC, farhan-arshad-dev approved these changes
some nits, other than that LGTM 🚀 .

2024-12-06 05:47 UTC, farhan-arshad-dev commented on course/src/main/java/org/openedx/course/data/repository/CourseRepository.kt
> +
extra line can be removed.

2024-12-06 05:47 UTC, farhan-arshad-dev commented on course/src/main/java/org/openedx/course/data/repository/CourseRepository.kt
> +    private var courseEnrollmentDetails = mutableMapOf<String, CourseEnrollmentDetails>()
`courseEnrollmentDetails` can local.

2024-12-06 17:56 UTC, merged