feat: Notifications Preferences Screen
edx/edx-mobile-marketplace-android pull request #76
Opened 2024-12-20 12:28 UTC by HamzaIsrar12

### Description

[LEARNER-10345](https://2u-internal.atlassian.net/browse/LEARNER-10345)

Add Push Notification settings to the profile, allowing users to manage permissions for discussion notifications.

### Screenshots

| Settings Screen | Push Notifications Screen |
|--------|--------|
|<img height=800 src="https://github.com/user-attachments/assets/2de03cd0-20ff-4718-a248-b535ac8381f1"/>|<img height=800 src="https://github.com/user-attachments/assets/ad5e6d4c-f9f7-4e9a-8aff-526d9f01f8b5"/>| 

### Config

PR: https://github.com/edx/edx-mobile-config/pull/188

2025-01-01 14:44 UTC, omerhabib26 requested changes
only some minor nits

2025-01-01 14:44 UTC, omerhabib26 commented on notifications/src/main/java/org/openedx/notifications/domain/model/NotificationsSettings.kt
> +data class NotificationsSettings(
IMO, we can rename it to `NotificationType` or `NotificationCategory`

2025-01-01 14:44 UTC, omerhabib26 commented on notifications/src/main/java/org/openedx/notifications/domain/interactor/NotificationsInteractor.kt
> +    suspend fun updateNotificationsConfiguration(value: Boolean): NotificationsUpdateResponse {
IMO, better to use an appropriate name for discussion flag.

2025-01-01 14:44 UTC, omerhabib26 commented on notifications/src/main/java/org/openedx/notifications/presentation/settings/NotificationsSettingsViewModel.kt
> +                logNotificationsEvent(
IMO, better to move it to a separate method and pass the flag only

2025-01-01 14:44 UTC, omerhabib26 commented on notifications/src/main/java/org/openedx/notifications/presentation/settings/NotificationsSettingsViewModel.kt
> +    @Suppress("SameParameterValue")
For the time being only a single event is triggering, so instead of adding an annotation, we can update the method.

2025-01-01 14:44 UTC, omerhabib26 commented on notifications/src/main/java/org/openedx/notifications/presentation/settings/NotificationsSettingsFragment.kt
> +                                .height(92.dp)
instead of fixing the height better to apply vertical padding for dynamically adjustment.

2025-01-02 13:08 UTC, omerhabib26 approved these changes

2025-01-09 12:40 UTC, k1rill approved these changes
LGTM, good job

2025-01-09 19:50 UTC, merged